import test from'node:test';import assert from'node:assert/strict';
import{create,transition,INITIAL,weather,SCENARIOS,previewTide}from'./model.mjs';
const step=(s,type,extra={})=>transition(s,{type,...extra});
function playable(seed=27){let s=create(seed);s=step(s,'build',{bay:0,kind:'quay'});s=step(s,'build',{bay:1,kind:'freight'});return s;}
function play(seed=27){let s=playable(seed);while(s.status==='playing'){for(const b of [...s.boats]){if(s.fuel<(b.kind==='barge'?2:1)&&s.coins>=4)s=step(s,'buy_fuel');s=step(s,'serve',{id:b.id});}
 if(s.bays[2]===null&&s.coins>=9){if(s.timber<3)s=step(s,'buy_timber');s=step(s,'build',{bay:2,kind:'breakwater'});}s=step(s,'end_tide');}return s;}
test('resource ledger conserves all fictional resources',()=>{const s=play();for(const k of Object.keys(INITIAL))assert.equal(s[k],INITIAL[k]+s.ledger.reduce((sum,x)=>sum+(x[k]||0),0));assert.ok(s.coins>=0&&s.timber>=0&&s.fuel>=0&&s.fuel<=10);});
test('deterministic seed, actions and weather',()=>{assert.deepEqual(play(27),play(27));assert.notDeepEqual(create(28),create(27));assert.equal(weather(27,2),weather(27,2));});
test('valid decisions can win after twelve tides',()=>{const s=play();assert.equal(s.status,'won');assert.equal(s.tide,12);assert.ok(s.delivered>=8&&s.coins>=60);});
test('neglect ends in observed in-game failure',()=>{let s=create();while(s.status==='playing')s=step(s,'end_tide');assert.equal(s.status,'lost');assert.ok(s.reputation<=0||s.tide===12);});
test('invalid placement and insufficient funds are atomic',()=>{const s=create();const original=structuredClone(s);assert.throws(()=>step(s,'build',{bay:4,kind:'quay'}));assert.throws(()=>step(s,'build',{bay:0,kind:'spaceship'}));assert.deepEqual(s,original);let poor=step(s,'build',{bay:0,kind:'freight'});poor=step(poor,'build',{bay:1,kind:'quay'});const before=structuredClone(poor);assert.throws(()=>step(poor,'build',{bay:2,kind:'freight'}));assert.deepEqual(poor,before);});
test('docks match vessels and have one service capacity per tide',()=>{const empty=create();assert.throws(()=>step(empty,'serve',{id:empty.boats[0].id}));let s=playable();const id=s.boats[0].id;s=step(s,'serve',{id});assert.equal(s.delivered,1);assert.throws(()=>step(s,'serve',{id}));assert.equal(s.served.length,1);});
test('restart clears every resource, vessel, event and outcome',()=>{const ended=play();assert.deepEqual(step(ended,'restart'),create(ended.seed));assert.equal(step(ended,'restart').ledger.length,0);});
test('breakwater prevents deterministic storm damage',()=>{let s=play();assert.equal(s.integrity,6);assert.ok(s.bays.includes('breakwater'));let unprotected=playable();while(weather(unprotected.seed,unprotected.tide)!=='storm'&&unprotected.status==='playing'){for(const b of [...unprotected.boats]){try{unprotected=step(unprotected,'serve',{id:b.id});}catch{}}unprotected=step(unprotected,'end_tide');}if(unprotected.status==='playing'){const before=unprotected.integrity;assert.equal(step(unprotected,'end_tide').integrity,before-1);}});
test('no external spending, paid services or real monetary reward',()=>{assert.equal(create().externalCost,0);assert.equal(play().externalCost,0);assert.equal(step(play(),'restart').externalCost,0);});
test('prototype properties cannot be used as a fabricated structure',()=>{for(const kind of ['constructor','toString','__proto__'])assert.throws(()=>step(create(),'build',{bay:0,kind}));});
test('second matching vessel cannot use a dock twice in one tide',()=>{let s=playable();const first=s.boats[0];s.boats.push({...first,id:'fixture-second'});s=step(s,'serve',{id:first.id});assert.throws(()=>step(s,'serve',{id:'fixture-second'}),/No matching unused dock/);assert.equal(s.delivered,1);});
test('every named scenario has a real winning sequence of permitted actions',()=>{for(const config of Object.values(SCENARIOS)){const s=play(config.seed);assert.equal(s.status,'won',config.label);assert.ok(s.coins>=config.goalCoins);assert.ok(s.delivered>=config.goalDeliveries);}});
test('tide preview matches actual consequences and never mutates current game',()=>{const s=playable();const before=structuredClone(s);const p=previewTide(s);const after=step(s,'end_tide');for(const k of ['coins','timber','fuel','integrity','reputation'])assert.equal(p[k],after[k]-s[k]);assert.equal(p.status,after.status);assert.deepEqual(s,before);});
test('storms stop fuel replenishment even behind breakwaters and upkeep still applies',()=>{let s=create(91);s.bays[2]='breakwater';while(weather(s.seed,s.tide)!=='storm'&&s.status==='playing')s=step(s,'end_tide');assert.equal(weather(s.seed,s.tide),'storm');const next=step(s,'end_tide');assert.equal(next.fuel,s.fuel);assert.equal(next.integrity,s.integrity);assert.equal(next.coins,s.coins-2);});
